"""add llm_usage table

Revision ID: 11381511e77a
Revises: 888ddd63ae9c
Create Date: 2026-09-01 11:32:46.158154

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11381511e77a"
down_revision: Union[str, Sequence[str], None] = "888ddd63ae9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    llm_provider_name = postgresql.ENUM(
        "GEMINI", "ANTHROPIC", name="llm_provider_name", create_type=False
    )
    llm_provider_name.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "llm_usage",
        sa.Column("provider", llm_provider_name, nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_usage_created_at"), "llm_usage", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_usage_created_at"), table_name="llm_usage")
    op.drop_table("llm_usage")

    # Drop ENUM type LAST (after the table that uses it)
    postgresql.ENUM(name="llm_provider_name", create_type=False).drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
