"""add user_id to llm_usage

Revision ID: 40fc9636de44
Revises: cf45892ce602
Create Date: 2026-10-01 16:20:54.816951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40fc9636de44"
down_revision: Union[str, Sequence[str], None] = "cf45892ce602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_usage", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_llm_usage_user_id"), "llm_usage", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_llm_usage_user_id_users",
        "llm_usage",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_llm_usage_user_id_users", "llm_usage", type_="foreignkey")
    op.drop_index(op.f("ix_llm_usage_user_id"), table_name="llm_usage")
    op.drop_column("llm_usage", "user_id")
    # ### end Alembic commands ###
