"""DB schema and models

Revision ID: 47a9d391ba7e
Revises: 0869ac62e218
Create Date: 2026-01-26 15:11:56.445072

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47a9d391ba7e"
down_revision: Union[str, Sequence[str], None] = "0869ac62e218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    application_stage = postgresql.ENUM(
        "SAVED",
        "APPLIED",
        "INTERVIEW",
        "OFFER",
        "REJECTED",
        "WITHDRAWN",
        name="application_stage",
        create_type=False,
    )
    activity_type = postgresql.ENUM(
        "NOTE",
        "OUTREACH",
        "FOLLOW_UP",
        "INTERVIEW",
        "OFFER",
        "REJECTION",
        name="activity_type",
        create_type=False,
    )
    bind = op.get_bind()
    application_stage.create(bind, checkfirst=True)
    activity_type.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("cognito_sub", sa.String(length=36), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_cognito_sub"), "users", ["cognito_sub"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("role_title", sa.String(length=128), nullable=False),
        sa.Column("job_url", sa.String(length=2000), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("salary_range", sa.String(length=100), nullable=True),
        sa.Column("stage", application_stage, nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stage_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_applications_user_last_activity",
        "applications",
        ["user_id", sa.literal_column("last_activity_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_applications_user_stage", "applications", ["user_id", "stage"], unique=False
    )
    op.create_table(
        "activities",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("activity_type", activity_type, nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activities_application_created_at",
        "activities",
        ["application_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_activities_application_id"),
        "activities",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_application_id"), table_name="activities")
    op.drop_index("ix_activities_application_created_at", table_name="activities")
    op.drop_table("activities")
    op.drop_index("ix_applications_user_stage", table_name="applications")
    op.drop_index("ix_applications_user_last_activity", table_name="applications")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_cognito_sub"), table_name="users")
    op.drop_table("users")

    # Drop ENUM types LAST (after tables that use them)
    bind = op.get_bind()
    activity_type = postgresql.ENUM(name="activity_type", create_type=False)
    application_stage = postgresql.ENUM(name="application_stage", create_type=False)

    activity_type.drop(bind, checkfirst=True)
    application_stage.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
