"""add parsed_jd to applications

Revision ID: 6975cbcc35a7
Revises: 7c4e2a9b1f3d
Create Date: 2026-09-16 15:06:04.008657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6975cbcc35a7"
down_revision: Union[str, Sequence[str], None] = "7c4e2a9b1f3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("parsed_jd", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "parsed_jd")
    # ### end Alembic commands ###
