"""user email nullable + activity occurred_at + defaults/indexes

Revision ID: 888ddd63ae9c
Revises: 47a9d391ba7e
Create Date: 2026-01-30 13:31:36.231192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "888ddd63ae9c"
down_revision: Union[str, Sequence[str], None] = "47a9d391ba7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.drop_index(op.f("ix_activities_application_created_at"), table_name="activities")
    op.create_index(
        "ix_activities_application_occurred_at",
        "activities",
        ["application_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_applications_user_updated_at",
        "applications",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=True
    )
    op.alter_column(
        "users",
        "cognito_sub",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="cognito_sub::uuid",
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "cognito_sub",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=False
    )
    op.drop_index("ix_applications_user_updated_at", table_name="applications")
    op.drop_index("ix_activities_application_occurred_at", table_name="activities")
    op.create_index(
        op.f("ix_activities_application_created_at"),
        "activities",
        ["application_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_column("activities", "occurred_at")
    # ### end Alembic commands ###
