"""add match_score and match_details to applications

Revision ID: 9145b8f7b946
Revises: 1d879e11846f
Create Date: 2026-09-16 16:42:33.185904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9145b8f7b946"
down_revision: Union[str, Sequence[str], None] = "1d879e11846f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("match_score", sa.Integer(), nullable=True))
    op.add_column(
        "applications",
        sa.Column(
            "match_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "match_details")
    op.drop_column("applications", "match_score")
    # ### end Alembic commands ###
